# Generated by Django 4.1 on 2024-05-12 14:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0005_user_delete_details"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
