

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: htf
    volumes:
      - .:/htf
    
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=htf.settings
